// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPlaylist.Persistence;

namespace NPlaylist.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190510070545_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.Audio", b =>
                {
                    b.Property<Guid>("AudioId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MetaAudioMetaId");

                    b.Property<Guid>("OwnerId");

                    b.Property<string>("Path");

                    b.Property<DateTime>("UtcCreatedTime");

                    b.HasKey("AudioId");

                    b.HasIndex("MetaAudioMetaId");

                    b.ToTable("AudioEntries");
                });

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.AudioMeta", b =>
                {
                    b.Property<Guid>("AudioMetaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Album");

                    b.Property<string>("Author");

                    b.Property<string>("Title");

                    b.HasKey("AudioMetaId");

                    b.ToTable("AudioMetaEntries");
                });

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.AudioPlaylists", b =>
                {
                    b.Property<Guid>("AudioId");

                    b.Property<Guid>("PlaylistId");

                    b.HasKey("AudioId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("AudioPlaylists");
                });

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.Playlist", b =>
                {
                    b.Property<Guid>("PlaylistId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid>("OwnerId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UtcDateTime");

                    b.HasKey("PlaylistId");

                    b.ToTable("PlaylistEntries");
                });

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.Audio", b =>
                {
                    b.HasOne("NPlaylist.Persistence.DbModels.AudioMeta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaAudioMetaId");
                });

            modelBuilder.Entity("NPlaylist.Persistence.DbModels.AudioPlaylists", b =>
                {
                    b.HasOne("NPlaylist.Persistence.DbModels.Audio", "Audio")
                        .WithMany("AudioPlaylists")
                        .HasForeignKey("AudioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NPlaylist.Persistence.DbModels.Playlist", "Playlist")
                        .WithMany("AudioPlaylists")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
